language: node_js

# https://benlimmer.com/2019/01/14/travis-ci-xvfb/
services:
  - xvfb

addons:
  chrome: stable

sudo: required

node_js:
  - '18'

before_script:
  - npm install

script:
  - npm run build
  - npm run test
